### ISSUE TITLE
Allow expectations that take `Query.Multiple`

### ISSUE THREAD

**Issue by hanneskaeufler** [avh4/elm-program-test#104]
I basically want to write this test:

```elm
                    ...
                    |> expectView
                        [ Query.findAll [ class "symbol-search-result" ]
                            |> Query.count (Expect.equal 2)
                        ]
```

This is shown as one of the examples in `elm-test`
https://package.elm-lang.org/packages/elm-explorations/test/latest/Test-Html-Query#findAll
but I cannot seem to translate that into `elm-program-test`. There is no way to get the html to pipe into `Query.fromHtml` either, right?

**Comment by avh4** [comment]
You should be able to do this with `ProgramTest.expectView`.  The first argument to `expectView` needs to be a function that will get called with basically what `Query.fromHtml` would give you in a non-elm-program-test test.

I think something like this should work:

```elm
                    ...
                    |> expectView
                        (Query.findAll [ class "symbol-search-result" ]
                            >> Query.count (Expect.equal 2)
                        )
```

(almost what you posted, but with `()` instead of `[]`, and `>>` instead of `|>`)

or if you want to avoid using `>>`, then something like

```elm
                    ...
                    |> expectView
                        (\body ->
                            body
                                |> Query.findAll [ class "symbol-search-result" ]
                                |> Query.count (Expect.equal 2)
                        )
```
