### ISSUE TITLE
test is looking for `for` but the attribute is set as `htmlFor`

### ISSUE THREAD

**Issue by BrianHicks** [avh4/elm-program-test#106]
It looks like the tests here are looking for "for" but virtual-dom sets "htmlFor". Yay javascript! Adjusting the expectation to search for either would probably work fine.

**Comment by BrianHicks** [comment]
sorry, I submitted this a little too early.

I have this call: `fillIn "server" "Server" "http://..."`

and this HTML is produced by Html.Styled as seen by Test.Html.Query:

```
<label class="_69727677" htmlFor="host">
    Host
    <input id="host" type="text" value="">
</label>
```

**Comment by avh4** [comment]
are you sure the HTML produced is actually valid?  I'm quite sure `Html.Attributes.for` currently works with elm-program-test.  In your example, the resulting HTML with the "htmlFor" removed would still work correctly in browsers because the input is nested inside the label.

Also, because your input is nested inside your label, you can simply use `fillIn "" "Host" "..."` and it should work (sorry that's not documented very well yet)

**Comment by BrianHicks** [comment]
hmm, strange. I'm pretty sure it's valid (validator.w3.org says this part of the page is valid.) All the `<input>`s are in a `<form>`, they all have unique IDs, et cetera.

the `fillIn "" "Host" "..."` doesn't work either, though. Curious 🤔

**Comment by BrianHicks** [comment]
ah, I figured it out: missing `onClick` handler. I missed that in the error message by jumping directly to the things it expected.

Thanks, and sorry for the noise!
