### ISSUE TITLE
Can this be used with Elm 0.19?

### ISSUE THREAD

**Issue by sporto** [avh4/elm-program-test#15]
Hi
This looks really useful, but I'm confused about the status of this project.
It is published as an Elm 0.19 package, which implies that it can be used with a 0.19 project.
But the Api and readme of the package seems to be all about Elm 0.18.

e.g. Readme me links to https://package.elm-lang.org/packages/elm-lang/navigation/latest/Navigation

In 0.19 you need a navKey in init, `flags -> Url -> Key -> ( model, Cmd msg )`
But `createWithNavigationAndFlags` doesn't provide that.

**Comment by avh4** [comment]
Currently the non-Navigation stuff works with Elm 0.19.  And also you can use it to test navigation programs, but not for functions that require a Navigation.Key, since currently Elm 0.19 does not provide any way to make a key for testing.

I'd be open to PRs that make the navigation stuff in this package better match the Elm 0.19 API.  But I've personally been waiting to look at that until Elm itself provides a way to create a Key when testing.

**Comment by sporto** [comment]
Thanks

**Comment by avh4** [comment]
An updated API that makes more sense with Elm 0.19's elm/browser package will be available in the upcoming 3.0.0 version.

**Comment by avh4** [comment]
v3.0.0 with the updated API to better match Elm 0.19 has been released.  See https://elm-program-test.netlify.com/upgrade-3.0.0.html for details

**Comment by avh4** [comment]
Also, while it's not very well documented, there is a note here about how to workaround Elm's limitations with testing things that need a Browser.Navigation.Key: https://package.elm-lang.org/packages/avh4/elm-program-test/3.0.0/ProgramTest#createApplication
