### ISSUE TITLE
Add support for navigation (load, reload, reloadAndSkipCache)

### ISSUE THREAD

**Issue by avh4** [avh4/elm-program-test#39]
This should add `load`, `reload`, and `reloadAndSkipCache` to `SimulatedEffect.Navigation` to parallel the functions in https://package.elm-lang.org/packages/elm/browser/latest/Browser-Navigation .  After those effects are simulated, they should result in `expectPageChange` to match the URL of the page that was loaded/reloaded.

If you are looking to contribute, feel free to make a PR that only implements one of these functions.    This is marked "good first issue", but you'd need to have a good understanding of using elm-program-test and of https://elm-program-test.netlify.com/cmds.html or else this probably won't be easy.

**Comment by jgrenat-personal-website** [comment]
Hello @avh4 ,

I'm trying to implement the `load` function, but I'm unsure how to handle one part of the code: using `Finished (ChangedPage "Navigation.load" url` expects an URL type and the `load` function takes a string as argument.

That means I need to parse the string to get an URL, which implies I need to handle the Maybe case. The solutions I could think are:

1. I change `ChangedPage` to take a String instead of an `Url`. As far as I can tell, there is no use for an `Url` because we're just using `Url.toString` everywhere
2. I add a new `ChangedPageString` variant that takes a String

Which one do you prefer?

**Comment by jgrenat** [comment]
Hello @avh4 

I'm trying to implement the `load` function, and I'm stuck on a part of the code. I need to change the state to `Finished (ChangedPage "Navigation.load" url)` but the `load` function takes a `String` and not a `Url`. That means I need to parse it and handle the `Maybe` if that fails. Currently, I think there are two options:

1. Change the `ChangedPage` variant to accept a `String` instead of an `Url` (the code only use this value as a String anyway for now)
2. Add a new variant `ChangedPageString` that accept a String

What do you think?

**Comment by avh4** [comment]
@jgrenat if I'm understanding the question correctly, then I think parsing the string into Url would be the way to go.  I guess I would wonder what happens in a real browser if you do a `load` with an invalid URL?   Does it actually try to resolve the string as a relative URL (if so, note the Url.Extra module in this project), or does it throw an error, or does it just silently do nothing?  We should try to mimic whatever real browsers would do.

**Comment by avh4** [comment]
This got implemented in #103
