### ISSUE TITLE
Mock Tests

### ISSUE THREAD

**Issue by Bernardoow** [avh4/elm-program-test#69]
Hi @avh4 !!

I was thinking how do the mock requests, so I did this tests: [Example mock](https://ellie-app.com/6BFnXKmLVsba1)  Line 135.

Do you have better approch to do this? Maybe this information could be add into documentation.

ps: I'm newer with testing. hehe

**Comment by avh4** [comment]
In that example, line 365 is where the data for the mocked request is specified by the test.  (Everything above line 343 is meant to be in the Main.elm instead of in the test file, but I had to combine them both into one to make the ellie-app example.)

Did you read through this guidebook already?  (I'm guessing you did, since that's where the example is from.)  I guess it doesn't do a good job yet of explaining how to write new tests after doing all the setup.

Whenever you call `ProgramTest.simulateHttpOk` in your test, the third argument will be the fake response body (which typically will be JSON) that will be used to mock the response to the request.

**Comment by Bernardoow** [comment]
Thanks @avh4 and sorry for took your time. 
I understood now.  
The lib is much better than I was thinking hehe !!
